name: Deploy to AWS

on:
  push:
    branches:
      - development
      - main
  pull_request:
permissions:
      id-token: write
      contents: read
      pull-requests: write
env:
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}

jobs:
  build-code:
    name: Build the Code
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build the Code
      id: job-step-build-code
      run: |
        echo "Building the code..."

        # Install the Dependencies
        yarn install

        # Build the application
        yarn run build

  configure-aws:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .
    
    steps:
      - name: Configure AWS credentials from AWS account
        id: job-step-aws-conf
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM    

  provision-infra:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /terraform

    steps:
      - name: Setup Terraform
        id: job-step-tf-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Format
        id: job-step-tf-fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Initialize
        id: job-step-tf-init
        run: terraform init 
            -backend-config="bucket=${{ env.AWS_BUCKET_NAME }}" 
            -backend-config="key=${{ env.AWS_BUCKET_KEY_NAME }}"
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        id: job-step-tf-validate
        run: terraform validate

      - name: Terraform Plan
        id: job-step-tf-plan
        run: terraform plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        continue-on-error: true