name: Deploy to AWS

on:
  push:
    branches:
      - development
      - main
  pull_request:
permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  build-code:
    name: Build the Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build the Code
      id: job-step-build-code
      run: |
        echo "Building the code..."

        # Install the Dependencies
        yarn install

        # Build the application
        yarn run build

        # Remove the Dependencies
        rm -rf node_modules

    - name: Store build output
      id: job-step-store-build-output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: .

  provision-infra:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    needs: [ build-code ]
    environment: development
    
    steps:
      - name: Configure AWS credentials from AWS account
        id: job-step-aws-conf
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM    

      - name: Download Build Output
        uses: actions/download-artifact@v3
        with:
          name: build-output
      
      - name: List All Files
        id: job-step-tf-list-files
        run: |
          ls -la

      - name: Setup Terraform
        id: job-step-tf-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Format
        id: job-step-tf-fmt
        run: terraform -chdir=./terraform fmt
        continue-on-error: true

      - name: Terraform Initialize
        id: job-step-tf-init
        env:
          AWS_BUCKET_NAME: ${{ env.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ env.AWS_BUCKET_KEY_NAME }}
        run: terraform -chdir=./terraform init 
            -backend-config="bucket=${AWS_BUCKET_NAME}" 
            -backend-config="key=${AWS_BUCKET_KEY_NAME}"
            -backend-config="region=${AWS_REGION}"

      - name: Select Existing/Create Terraform Workspace
        id: job-step-tf-init-workspace
        env:
          TERRAFORM_WORKSPACE: ${{ env.ENVIRONMENT }}
        run: |
          if $(terraform -chdir=./terraform workspace list | grep -q "${TERRAFORM_WORKSPACE}") ; 
          then terraform -chdir=./terraform workspace select ${TERRAFORM_WORKSPACE}; 
          else terraform -chdir=./terraform workspace new ${TERRAFORM_WORKSPACE}; fi

      - name: Show Current Workspace
        id: job-step-tf-show-workspace
        run: terraform -chdir=./terraform workspace show

      - name: Terraform Validate
        id: job-step-tf-validate
        run: terraform -chdir=./terraform validate

      - name: Terraform Plan
        id: job-step-tf-plan
        run: terraform -chdir=./terraform plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        continue-on-error: true